version: "3.9"
services:
  app:
    # image: ruby
    build: .
    volumes:
    - ./:/app
    ports:
    - "3000:3000"
    command: tail -f /dev/null
    environment:
      - DATABASE_URL_DEV=postgres://username:password@postgres:5432/dbname
      - DATABASE_URL_TEST=postgres://username:password@postgres:5432/test_dbname
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

volumes:
  postgres: {}